### ISSUE TITLE
[RAML 1.0] Inheritance of types

### ISSUE THREAD

**Issue by iwex** [raml2html/raml2obj#15]
Could you please add inheritance of types, so we can see all properties: for current type and its parents.

**Comment by alexnitta** [comment]
Here's a detailed example of how this plays out with Response documentation.

I'm converting a RAML 1.0 file with `raml2html` version 4.0.0-beta7, which uses `raml2obj`. I noticed that any Query Parameter that lists a type that inherits from another type will display the parent type instead of the child type. This happened when running `raml2html` from the command line with the default template.

For example, the `OutputResource` type lists the properties `completed` and `counters`. `counters` uses the `resource` type, which inherits from `base`. Instead of seeing the name and description of `counters` in the HTML output, we see the name and description of `base.` Similarly, instead of seeing the name and description of `rel`, we see the name and description of `base`.

This is related to the ongoing discussion of RAML 1.0 implementation in https://github.com/raml2html/raml2html/issues/254


Source code:

**HTML output for Response tab content:**

HTTP status code 200

Body

Media type: application/json

Type: object

Properties
abort_message: required (string)
Reason why this output was aborted, if any.

aborted: required (boolean)
True when generation was aborted.

completed: required (boolean)
True when generation is complete.

base: required (object)
The base class for all Fields and Arguments. Field objects are used by Resources to define the data they return. They include a name, a type, a short description, and a long description. Of these instance variables, only name is functionally significant, as it's used as the key for the field's value in the outgoing JSON. The rest of the instance variables are used to generate documentation. Argument objects inherit from Field, in that they share the same base set of instance variables, but are used on the input side of the API, and include validation functionality. .

id: required (string)
ID for this operation.

base: required (object)
The base class for all Fields and Arguments. Field objects are used by Resources to define the data they return. They include a name, a type, a short description, and a long description. Of these instance variables, only name is functionally significant, as it's used as the key for the field's value in the outgoing JSON. The rest of the instance variables are used to generate documentation. Argument objects inherit from Field, in that they share the same base set of instance variables, but are used on the input side of the API, and include validation functionality. .

signed_download_url: required (string)
Signed, expiring link to download this output.

signed_public_access_url: required (string)
URL for public access to this report. Expires after 2 weeks.

status_url: required (string)
URL for status of this operation.

style: required (string)
Style of output.

**Type:**
```RAML
  OutputResource:
    description: An output object.
    properties:
      abort_message:
        type: string
        description: Reason why this output was aborted, if any.
      aborted:
        type: boolean
        description: True when generation was aborted.
      completed:
        type: boolean
        description: True when generation is complete.
      counters:
        type: resource
        description: Counters generated during process.
        properties:
      id:
        type: string
        description: ID for this operation.
      rel:
        type: relative_links
        description: URIs.
      signed_download_url:
        type: string
        description: Signed, expiring link to download this output.
      signed_public_access_url:
        type: string
        description: URL for public access to this report. Expires after 2 weeks.
      status_url:
        type: string
        description: URL for status of this operation.
      style:
        type: string
        description: Style of output.
```

**Endpoint:**
```RAML
/admin:
  /catalog_dump:
    post:
      description: Returns a Pipeline Output object for a given access token.
      queryParameters:
        creator:
          type: string
          required: false
          description: Payee key of an artist on the catalogs.
        secret:
          type: string
          required: false
          description: API Secret Token.
      responses:
        200:
          body:
            type: OutputResource
            description: Output status object.
```

**Comment by kevinrenskers** [comment]
This should be fixed in raml2obj 4.0.0-beta9.
raml2html 4.0.0-beta8 was also just released which uses the new raml2obj.

Please test and let me know how it works for you. There is a known issue regarding array types where the child properties are not displayed, but this looks like a bug in the `datatype-expansion` library.

**Comment by alexnitta** [comment]
Looks like the fix mostly works - thanks for your quick action on this. It does use the child properties as expected. The only wrinkle is that they appear out of order with respect to the RAML file. The `properties` of `OutputResource` should appear in alphabetical order, but they do not. The ones that use child properties are listed before the others.

Here's the current HTML output created with raml2html 4.0.0-beta8

HTTP status code 200

Body

Media type: application/json

Type: object

Properties
rel: required (object)
URIs.

completed: required (boolean)
True when generation is complete.

aborted: required (boolean)
True when generation was aborted.

abort_message: required (string)
Reason why this output was aborted, if any.

counters: required (object)
Counters generated during process.

style: required (string)
Style of output.

signed_download_url: required (string)
Signed, expiring link to download this output.

id: required (string)
ID for this operation.

status_url: required (string)
URL for status of this operation.

signed_public_access_url: required (string)
URL for public access to this report. Expires after 2 weeks.

**Comment by alexnitta** [comment]
Checking back on this, I'm now seeing that child properties are shown differently in GET requests vs. POST requests. Things render mostly as expected for POST requests - which is what I was seeing in the prior comment. However, a GET request still shows the wrong output. It shows the name and description of the parent type, rather than the child type.

For example:

**Child type:**

```RAML
  PaginatedResourceList:
    description: Results of a query.
    properties:
      cursor:
        type: array
        items: base
        description: Cursor, used for paginating a query.
      parsed_query:
        type: resource
        description: Parsed output of query passed.
        properties:
[...etc]
```

**Parent type:**

```RAML
  resource:
    type: base
    description: A field that contains a nested resource.
```

**HTML:**

HTTP status code 200

Body

Media type: application/json

Type: object

Properties
cursor: required (array)
Cursor, used for paginating a query.

resource: required (object)
A field that contains a nested resource.

relative_links: required (object)
A field that contains relative links to a Resource. This field is inherently a list of relative links, but it's special in that it accepts a list of methods that get called to generate the links. Each of these link generation methods should return a tuple with the name of the relative link, as well as the url, i.e. ('canonical', 'https://github.com/Loudr/pale') The resulting field will render as an object of named URLs, like this= 'rel'= { 'canonical'= 'https://github.com/Loudr/pale' }.

results: required (array)
List of resulting resources.

total: required (integer)
Estimated total number of results.

**Comment by alexnitta** [comment]
FYI, te above example is from raml2html@4.0.0-beta14.

**Comment by kevinrenskers** [comment]
I am going to close old issues, and will ask that new bug reports instead be created as a pull request with a failing unit test. Sorry, but I just don't have the time and energy to do it all alone :/

See also https://github.com/raml2html/raml2obj/blob/develop/CONTRIBUTING.md. Thanks!
